<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="NI.Discovery.V1.Client" Version="9.21.0.2789" />
    <PackageVersion Include="NI.Measurements.MetadataBuilder" Version="9.21.0.2789-ci.2606282318" />
  </ItemGroup>

</Project>