<Project>

  <ItemGroup Condition="@(PackageReference->AnyHaveMetadataValue('Identity','NationalInstruments.Core.TestUtilities'))">
    <Using Include="NationalInstruments.TestUtilities.Core" />
    <Using Include="NationalInstruments.TestUtilities.Core.TheorySupport" />
    <Using Include="NationalInstruments.TestUtilities.Mixins" />
    <Using Include="NationalInstruments.TestUtilities.Unit.Mixins" />
  </ItemGroup>

</Project>