<Project>
  <PropertyGroup>
    <!--
      Ignore NuGet warnings about missing framework references.
      Some of our packages still only target .NET Framework
      -->
    <NoWarn>$(NoWarn);NU1701;NU1603</NoWarn>

    <!-- Enable building these projects on Linux. -->
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup>
    <IsTestProject>$([System.String]::Copy('$(MSBuildProjectName)').StartsWith('Tests.'))</IsTestProject>
    <IsTestUtilityProject>$([System.String]::Copy('$(MSBuildProjectName)').StartsWith('TestUtilities.'))</IsTestUtilityProject>

    <AppTargetFramework>net8.0-windows</AppTargetFramework>
    <TestTargetFramework>net8.0</TestTargetFramework>
    <WindowsTestTargetFramework>net8.0-windows</WindowsTestTargetFramework>

    <ExamplesRootDirectory>$(MSBuildThisFileDirectory)</ExamplesRootDirectory>
    <ExamplesSrcDirectory>$(ExamplesRootDirectory)src\</ExamplesSrcDirectory>
    <BinariesRootDirectory>$(ExamplesRootDirectory).binaries\</BinariesRootDirectory>
    <BinariesSubDirectory Condition="'$(IsTestProject)' == 'true'">Tests\</BinariesSubDirectory>

    <BaseOutputPath>$(BinariesRootDirectory)$(BinariesSubDirectory)$(MSBuildProjectName)\</BaseOutputPath>
    <PublishDir>$(BinariesRootDirectory)Publish\$(MSBuildProjectName)\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\</PublishDir>

    <ObjectsRootDirectory>$(ExamplesRootDirectory).objects\</ObjectsRootDirectory>
    <BaseIntermediateOutputPath>$(ObjectsRootDirectory)$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>

</Project>