<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ASWPackageVersion>9.20.0.2095</ASWPackageVersion>
    <MDSPackageVersion>9.20.0-ci.2602252004</MDSPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="NationalInstruments.SystemConfiguration.x64" Version="26.0.49263" />
    <PackageVersion Include="NI.DataStore.V1" Version="9.21.0.2575-ci.2606161932" />
  </ItemGroup>

</Project>