<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>QueryExample</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NI.DataStore.V1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataStoreContext\DataStoreContext.csproj" />
  </ItemGroup>

</Project>
